---
- name: Playbook
  hosts: all
  become: true
  tasks:
    - name: copy the war
      copy:
        src: /home/ans/jenkins/helloworld-0.0.1-SNAPSHOT.war
        dest: /opt/apache-tomcat-8.5.55/webapps/
      

