---
- name: Playbook
  hosts: all
  become: true
  tasks:
    - name: copy the war
      copy:
        src: /var/lib/jenkins/workspace/Pipeline/target/*.war
        dest: /opt/apache-tomcat-8.5.55/webapps
      

